In [11]:
import numpy as np

In [ ]:
py_list = [[1,2,3,4,5],[6,7,8,9,10]]
np_arr = np.array(py_list)
np_arr

In [9]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###  Another Methods for Createing Numpy array

In [14]:
np.zeros((4,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
np.ones((3,4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Creating 3D Martrix

In [21]:
np.full((3,4,5),10) 

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

### Useing eye method() its work like squear Ears

In [3]:
np.eye(5, dtype="int")

NameError: name 'np' is not defined

### This  is selected Pointer from list

In [35]:
np.linspace(10,-1,6)

array([10. ,  7.8,  5.6,  3.4,  1.2, -1. ])

In [40]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
np.random.rand(2,2,2)

array([[[0.4993824 , 0.25097614],
        [0.97688364, 0.30121305]],

       [[0.4285377 , 0.52325327],
        [0.49077751, 0.3053355 ]]])

In [86]:
arr = np.random.randint(0,11,6)
arr

array([ 2,  6,  7, 10,  4, 10])

In [87]:
arr.reshape(2,3) 

array([[ 2,  6,  7],
       [10,  4, 10]])

### Max number of array and Max Number index Number 

In [98]:
arr = np.random.randint(0,100,(5,5))
print(arr)
print(arr.max())
print(arr.argmax())

[[92 23 58 14 81]
 [ 2 90 18 87 70]
 [20 64 43 57 27]
 [34 89 73 77 73]
 [16 51 67 79 95]]
95
24


### Minimum Numeber form array and indexing number

In [2]:
arr = np.random.randint(0,100,(3,5))
print(arr)
print(arr.min())
print(arr.argmin())

NameError: name 'np' is not defined

In [115]:
arr.shape

(3, 5)

In [116]:
arr.ndim

2

In [117]:
arr.size

15

In [1]:
arr.dtype

NameError: name 'arr' is not defined

In [3]:
import numpy as np

In [5]:
arr = np.random.randint(0,100,(3,5))
print(arr)

[[61 99 36 94 59]
 [92 83 53 23 95]
 [35 34 18 19 70]]


In [9]:
# arr.size
arr.itemsize

8

### Memory copy

In [48]:
sample_arr = np.random.randint(0,100,10)
sample_arr

array([29, 12, 13, 31, 58, 80, 17, 84,  3, 20])

In [49]:
new_arr = sample_arr.copy()
new_arr

array([29, 12, 13, 31, 58, 80, 17, 84,  3, 20])

In [41]:
print(sample_arr.data)
print(new_arr.data)

In [50]:
new_arr[:5] = 100
new_arr

array([100, 100, 100, 100, 100,  80,  17,  84,   3,  20])

In [54]:
sample_arr

array([29, 12, 13, 31, 58, 80, 17, 84,  3, 20])

### Showing 2D arry data


In [57]:
arr_2d = np.random.randint(0,100,(5,5))
arr_2d

array([[94, 52, 52, 69, 55],
       [ 9, 36, 28,  2, 32],
       [20, 16, 53, 79, 22],
       [33, 21, 73, 83, 94],
       [ 5, 44, 40, 23, 21]])

In [61]:
arr_2d[2][2]

53

In [63]:
arr_2d[2,2]

53

### 2D array Slicing 

In [68]:
arr_2d = np.random.randint(0,100,(5,5))
arr_2d

array([[83, 10,  0,  3, 90],
       [61, 63, 92, 40, 71],
       [96, 35, 68, 41,  1],
       [30, 55, 88, 72, 81],
       [89, 35, 58, 61,  4]])

In [72]:
arr_slice = arr_2d[1:3,1:]
arr_slice

array([[63, 92, 40, 71],
       [35, 68, 41,  1]])

### Condition chack

In [75]:
data = np.random.randint(0,11,10)
data

array([ 5,  7, 10,  7,  4,  6,  5,  9,  1,  4])

In [78]:
data[data>4]

array([ 5,  7, 10,  7,  6,  5,  9])

### Array Mathmatical Equtions


In [88]:
arr1 = np.arange(0,12).reshape(4,3)
arr2 = np.arange(10,22).reshape(4,3)
np.add(arr1,arr2)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32]])